

r"""
MPO constructors
----------------

This module contains two related fermionic MPO constructions.

The spinful one-dimensional Hubbard constructor represents each lattice site
with the four-state basis

.. math::

    |0\rangle,\quad |\uparrow\rangle,\quad |\downarrow\rangle,\quad
    |\uparrow\downarrow\rangle,

and builds a nearest-neighbor finite-state MPO for the local-operator form

.. math::

    H_{\mathrm{Hub,MPO}} =
    U \sum_i n_{i\uparrow} n_{i\downarrow}
    + t \sum_i \Big[
        c^\dagger_{i\uparrow}\widetilde c_{i+1,\uparrow}
        + c^\dagger_{i\downarrow}\widetilde c_{i+1,\downarrow}
        - c_{i\uparrow}\widetilde c^\dagger_{i+1,\uparrow}
        - c_{i\downarrow}\widetilde c^\dagger_{i+1,\downarrow}
      \Big],

where :math:`\widetilde c_{i\sigma}=c_{i\sigma}P_i` and
:math:`P_i=(-1)^{n_{i\uparrow}+n_{i\downarrow}}`.  This is the finite-state
MPO representation of nearest-neighbor Hubbard hopping in the local spinful
site basis; the sign convention is set by the input hopping parameter ``t``.

The ab initio/quantum-chemistry constructors start from one- and two-electron
spin-orbital integrals,

.. math::

    H =
    \sum_{pq} h_{pq} a^\dagger_p a_q
    + {1 \over 2}\sum_{pqrs} h_{pqrs}
      a^\dagger_p a^\dagger_q a_r a_s,

then:

1. map each fermionic monomial to a Jordan-Wigner product of local operators;
2. collect identical local operator strings and their scalar coefficients;
3. encode the resulting sum of product operators as an exact open-boundary MPO.

The generic construction uses a prefix tree/finite-state-machine layout, which
is standard MPO practice :cite:`Hubig:2017gc`.  The compact constructor uses the
same exact local strings but reuses both left and right substrings through
fork/merge bond labels.
"""

# fermionic 2nd quantization --> MPO constructor

import numpy as np
from collections import defaultdict
from dataclasses import dataclass
from typing import Dict, List, Tuple, Any
from ttqd.lib import deprecated
from ttqd.operator.mpo import MPO


# 1) Fermi-Hubbard U model

def hubbard_local_operators():
    r"""
    Return local operators for one spinful Hubbard site.

    The local basis is ordered as

    .. math::

        |0\rangle,\quad |\uparrow\rangle,\quad |\downarrow\rangle,\quad
        |\uparrow\downarrow\rangle.

    The matrices named ``a*`` are the single-site fermionic ladder operators in
    this basis.  The matrices named ``a*Par`` include a right local parity
    factor,

    .. math::

        \widetilde c_{i\sigma} = c_{i\sigma} P_i,\qquad
        P_i = (-1)^{n_{i\uparrow}+n_{i\downarrow}},

    and are used by :func:`make_hubbard_mpo` to close nearest-neighbor hopping
    paths with the correct fermionic signs in the spinful site basis.
    ``nUpnDn`` is :math:`n_{i\uparrow} n_{i\downarrow}`.
    """
    I = np.identity(4, dtype=np.complex128)
    Z = np.zeros((4, 4), dtype=np.complex128)
    aDagUp = np.array(
        [[0, 0, 0, 0],
         [1, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 1, 0]],
        dtype=np.complex128,
    )
    aDagUpPar = np.array(
        [[0, 0, 0, 0],
         [1, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, -1, 0]],
        dtype=np.complex128,
    )
    aDagDn = np.array(
        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [1, 0, 0, 0],
         [0, -1, 0, 0]],
        dtype=np.complex128,
    )
    aDagDnPar = np.array(
        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [1, 0, 0, 0],
         [0, 1, 0, 0]],
        dtype=np.complex128,
    )
    aUp = np.array(
        [[0, 1, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 1],
         [0, 0, 0, 0]],
        dtype=np.complex128,
    )
    aUpPar = np.array(
        [[0, -1, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 1],
         [0, 0, 0, 0]],
        dtype=np.complex128,
    )
    aDn = np.array(
        [[0, 0, 1, 0],
         [0, 0, 0, -1],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],
        dtype=np.complex128,
    )
    aDnPar = np.array(
        [[0, 0, -1, 0],
         [0, 0, 0, -1],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],
        dtype=np.complex128,
    )
    nUpnDn = np.array(
        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 1]],
        dtype=np.complex128,
    )
    return {
        "I": I,
        "Z": Z,
        "aDagUp": aDagUp,
        "aDagUpPar": aDagUpPar,
        "aDagDn": aDagDn,
        "aDagDnPar": aDagDnPar,
        "aUp": aUp,
        "aUpPar": aUpPar,
        "aDn": aDn,
        "aDnPar": aDnPar,
        "nUpnDn": nUpnDn,
    }


def make_hubbard_mpo(N, t, u, ops=None):
    r"""
    Construct the nearest-neighbor one-dimensional Hubbard MPO.

    The local-operator Hamiltonian generated by the MPO is

    .. math::

        H_{\mathrm{MPO}} =
        U \sum_{i=0}^{N-1} n_{i\uparrow}n_{i\downarrow}
        + t \sum_{i=0}^{N-2} \Big[
          c^\dagger_{i\uparrow}\widetilde c_{i+1,\uparrow}
          + c^\dagger_{i\downarrow}\widetilde c_{i+1,\downarrow}
          - c_{i\uparrow}\widetilde c^\dagger_{i+1,\uparrow}
          - c_{i\downarrow}\widetilde c^\dagger_{i+1,\downarrow}
        \Big],

    with :math:`\widetilde c_{i\sigma}=c_{i\sigma}P_i` and
    :math:`P_i=(-1)^{n_{i\uparrow}+n_{i\downarrow}}`.

    The sign convention is controlled by the value passed as ``t``.  For a
    convention with an overall negative hopping amplitude, pass a negative
    value of ``t``.

    The bulk MPO tensor has virtual channels

    .. math::

        \left[I,\ c^\dagger_\uparrow,\ c^\dagger_\downarrow,\ c_\uparrow,
        c_\downarrow,\ \mathrm{done}\right],

    so a hopping term is generated by opening a channel on site :math:`i` and
    closing it on site :math:`i+1`.  The onsite interaction uses the direct
    transition from the identity channel to the done channel:

    .. math::

        W =
        \begin{pmatrix}
        I & c^\dagger_\uparrow & c^\dagger_\downarrow & c_\uparrow
          & c_\downarrow & U n_\uparrow n_\downarrow \\
        0 & 0 & 0 & 0 & 0 & t \widetilde c_\uparrow \\
        0 & 0 & 0 & 0 & 0 & t \widetilde c_\downarrow \\
        0 & 0 & 0 & 0 & 0 & -t \widetilde c^\dagger_\uparrow \\
        0 & 0 & 0 & 0 & 0 & -t \widetilde c^\dagger_\downarrow \\
        0 & 0 & 0 & 0 & 0 & I
        \end{pmatrix}.

    Parameters
    ----------
    N : int
        Number of spinful lattice sites.
    t : complex or float
        Hopping amplitude in the sign convention above.
    u : complex or float
        Onsite Hubbard interaction strength.
    ops : dict, optional
        Operator dictionary from :func:`hubbard_local_operators`.

    Returns
    -------
    MPO
        Boundary-shaped MPO with physical dimension four at each site.
    """
    if ops is None:
        ops = hubbard_local_operators()
    I = ops["I"]
    Z = ops["Z"]
    aDagUp = ops["aDagUp"]
    aDagDn = ops["aDagDn"]
    aUp = ops["aUp"]
    aDn = ops["aDn"]
    aUpPar = ops["aUpPar"]
    aDnPar = ops["aDnPar"]
    aDagUpPar = ops["aDagUpPar"]
    aDagDnPar = ops["aDagDnPar"]
    nUpnDn = ops["nUpnDn"]

    W = np.array(
        [[I, aDagUp, aDagDn, aUp, aDn, u * nUpnDn],
         [Z, Z, Z, Z, Z, t * aUpPar],
         [Z, Z, Z, Z, Z, t * aDnPar],
         [Z, Z, Z, Z, Z, -t * aDagUpPar],
         [Z, Z, Z, Z, Z, -t * aDagDnPar],
         [Z, Z, Z, Z, Z, I]],
        dtype=np.complex128,
    )
    Wfirst = np.array([[I, aDagUp, aDagDn, aUp, aDn, u * nUpnDn]], dtype=np.complex128)
    Wlast = np.array(
        [[u * nUpnDn], [t * aUpPar], [t * aDnPar], [-t * aDagUpPar], [-t * aDagDnPar], [I]],
        dtype=np.complex128,
    )
    Wlist = [Wfirst] + ([W.copy()] * (N - 2)) + [Wlast]
    return MPO(Wlist)



# 2) ------- general quantum-chemistry Hamiltonian (with OEI and ERI) ---------
# direct implementation

@deprecated   # replaced by local_fermion_ops
def _site_ops(dtype=np.complex128):
    """
    Local basis: |0>, |1>
    """
    I = np.eye(2, dtype=dtype)
    F = np.array([[1, 0],
                  [0, -1]], dtype=dtype)   # fermion parity (-1)^n
    c = np.array([[0, 1],
                  [0, 0]], dtype=dtype)    # annihilation
    cd = np.array([[0, 0],
                   [1, 0]], dtype=dtype)   # creation
    return I, F, c, cd


# =========================
# local JW operators
# =========================

def local_fermion_ops(dtype=np.complex128):
    r"""
    Return local Jordan-Wigner operators for one spin orbital.

    Each ab initio MPO site is one spin orbital with basis
    :math:`|0\rangle, |1\rangle`.  The local matrices are

    .. math::

        I =
        \begin{pmatrix}1&0\\0&1\end{pmatrix},\qquad
        F = (-1)^n =
        \begin{pmatrix}1&0\\0&-1\end{pmatrix},

    .. math::

        c =
        \begin{pmatrix}0&1\\0&0\end{pmatrix},\qquad
        c^\dagger =
        \begin{pmatrix}0&0\\1&0\end{pmatrix},\qquad
        n = c^\dagger c.

    The global fermionic operator on site :math:`p` is represented by a
    Jordan-Wigner string,

    .. math::

        a_p = F_0 F_1 \cdots F_{p-1} c_p,\qquad
        a^\dagger_p = F_0 F_1 \cdots F_{p-1} c^\dagger_p.
    """
    I = np.eye(2, dtype=dtype)
    F = np.array([[1, 0],
                  [0, -1]], dtype=dtype)          # parity
    c = np.array([[0, 1],
                  [0, 0]], dtype=dtype)           # annihilation
    cd = np.array([[0, 0],
                   [1, 0]], dtype=dtype)          # creation
    n = cd @ c
    zc = np.zeros((2, 2), dtype=dtype)
    return {
        "I": I,
        "F": F,
        "c": c,
        "cd": cd,
        "n": n,
        "0": zc,
    }


def _mat_key(mat, tol=1e-14):
    """
    Hashable key for a 2x2 matrix.
    """
    m = np.array(mat, dtype=np.complex128, copy=True)
    m[np.abs(m) < tol] = 0.0
    return tuple(m.ravel())


def _key_to_mat(key):
    return np.array(key, dtype=np.complex128).reshape(2, 2)


def jw_local_string(n_sites, ops, dtype=np.complex128):
    r"""
    Convert a fermionic monomial to a list of local 2x2 operators
    using Jordan-Wigner strings.

    For a monomial in the explicit operator order

    .. math::

        M = a^\sharp_{p_1} a^\sharp_{p_2}\cdots a^\sharp_{p_m},

    where :math:`\sharp` means either creation or annihilation, this routine
    multiplies the corresponding local Jordan-Wigner factors site by site:

    .. math::

        M \mapsto O_0 \otimes O_1 \otimes \cdots \otimes O_{K-1}.

    Repeated operators on the same site are multiplied locally in the same
    order as the fermionic monomial.  Nilpotent products such as
    :math:`c_p c_p = 0` therefore become a zero local operator and are later
    dropped by the MPO builders.

    Parameters
    ----------
    n_sites : int
    ops : list[tuple[int, bool]]
        [(site, dagger), ...] in the exact operator order appearing
        in the monomial.
        dagger=True  -> a^\dagger_site
        dagger=False -> a_site

    Returns
    -------
    local_ops : list[np.ndarray]
        local_ops[i] is the 2x2 operator acting on site i.
    """
    site_ops = local_fermion_ops(dtype)
    I = site_ops["I"]
    F = site_ops["F"]
    c = site_ops["c"]
    cd = site_ops["cd"]
    local = [I.copy() for _ in range(n_sites)]

    for site, dagger in ops:
        if not (0 <= site < n_sites):
            raise IndexError(f"site {site} out of range for n_sites={n_sites}")

        # Jordan-Wigner parity string on all earlier sites
        for j in range(site):
            local[j] = local[j] @ F

        # Local ladder operator
        local[site] = local[site] @ (cd if dagger else c)

    return local


def second_quantized_to_mpo(h1, h2, tol=1e-14, dtype=np.complex128):
    r"""
    Build an exact prefix-tree MPO for a spin-orbital ab initio Hamiltonian.

    .. math::

        H =
        \sum_{pq} h_{pq} a_p^\dagger a_q
        + {1 \over 2}\sum_{pqrs} h_{pqrs}
          a_p^\dagger a_q^\dagger a_r a_s.

    ``h1`` stores :math:`h_{pq}` and ``h2`` stores :math:`h_{pqrs}` in the
    same operator order used in the equation.  Each nonzero integral contributes
    one fermionic monomial,

    .. math::

        h_{pq} a^\dagger_p a_q,\qquad
        {1 \over 2} h_{pqrs} a^\dagger_p a^\dagger_q a_r a_s,

    which is converted to a local Jordan-Wigner string

    .. math::

        \alpha_\ell\,
        O^{(\ell)}_0 \otimes O^{(\ell)}_1 \otimes \cdots
        \otimes O^{(\ell)}_{K-1}.

    Identical local strings are summed before the MPO is built.  The prefix-tree
    construction creates one virtual state for each distinct prefix
    :math:`(O^{(\ell)}_0,\ldots,O^{(\ell)}_{i-1})`.  A path through the MPO is

    .. math::

        \emptyset
        \xrightarrow{O^{(\ell)}_0}
        (O^{(\ell)}_0)
        \xrightarrow{O^{(\ell)}_1}
        \cdots
        \xrightarrow{\alpha_\ell O^{(\ell)}_{K-1}}
        \mathrm{sink},

    so contracting all tensors sums exactly over all Hamiltonian product
    strings.

    Parameters
    ----------
    h1 : (K,K) ndarray
        One-electron integral tensor :math:`h_{pq}`.
    h2 : (K,K,K,K) ndarray
        Two-electron tensor :math:`h_{pqrs}` in the order
        :math:`a^\dagger_p a^\dagger_q a_r a_s`.
    tol : float
        Numerical threshold for dropping tiny terms.
    dtype : numpy dtype

    Returns
    -------
    Ws : list[np.ndarray]
        Ws[i] has shape (D_left_i, D_right_i, 2, 2).
        The Hamiltonian is reconstructed as the MPO contraction of this list.
    """
    h1 = np.asarray(h1, dtype=dtype)
    h2 = np.asarray(h2, dtype=dtype)

    if h1.ndim != 2 or h1.shape[0] != h1.shape[1]:
        raise ValueError("h1 must have shape (K,K)")
    K = h1.shape[0]

    # TODO: use chols to reduce memeory
    if h2.shape != (K, K, K, K):
        raise ValueError("h2 must have shape (K,K,K,K)")

    # path_coeff[path] = coefficient for one full local operator string
    # A path is a tuple of K matrix-keys, one for each site.
    path_coeff = defaultdict(complex)

    def add_term(coeff, fermion_ops):
        coeff = complex(coeff)
        if abs(coeff) < tol:
            return

        local = jw_local_string(K, fermion_ops, dtype=dtype)

        # Nilpotent cases (e.g. c^2 = 0) lead to a zero local operator somewhere.
        if any(np.all(np.abs(op) < tol) for op in local):
            return

        #for op in local:
        #    print("op = ", op)
        path = tuple(_mat_key(op, tol=tol) for op in local)
        path_coeff[path] += coeff

    # One-body terms
    for p, q in np.argwhere(np.abs(h1) > tol):
        add_term(h1[p, q], [(p, True), (q, False)])

    # Two-body terms
    # The Hamiltonian in the user's formula has the prefactor 1/2 outside the sum.
    for p, q, r, s in np.argwhere(np.abs(h2) > tol):
        # print("\ndebug: pqrs = ", p, q, r, s)
        add_term(0.5 * h2[p, q, r, s],
                 [(p, True), (q, True), (r, False), (s, False)])
    # exit()

    # Remove cancellations
    path_coeff = {path: coeff for path, coeff in path_coeff.items()
                  if abs(coeff) > tol}

    # Zero Hamiltonian -> trivial zero MPO
    if not path_coeff:
        return [np.zeros((1, 1, 2, 2), dtype=dtype) for _ in range(K)]

    # Special case K=1
    if K == 1:
        W = np.zeros((1, 1, 2, 2), dtype=dtype)
        for path, coeff in path_coeff.items():
            W[0, 0] += coeff * _key_to_mat(path[0])
        W[np.abs(W) < tol] = 0.0
        return [W]

    # prefix_layers[d] maps a prefix of length d to its bond index at layer d
    # layer 0 contains only the empty prefix
    prefix_layers = [{(): 0}] + [dict() for _ in range(K - 1)]

    # transitions[i][(a,b)] = local 2x2 operator on site i connecting
    # bond state a at layer i to bond state b at layer i+1
    transitions = [dict() for _ in range(K)]

    for path, coeff in path_coeff.items():
        prefix = ()

        # Sites 0..K-2 create / follow prefix-tree states
        for i in range(K - 1):
            cur_idx = prefix_layers[i][prefix]

            next_prefix = prefix + (path[i],)
            next_layer = prefix_layers[i + 1]
            if next_prefix not in next_layer:
                next_layer[next_prefix] = len(next_layer)
            next_idx = next_layer[next_prefix]

            op = _key_to_mat(path[i])

            # This edge may be revisited by many different full strings that share the prefix.
            old = transitions[i].get((cur_idx, next_idx))
            if old is None:
                transitions[i][(cur_idx, next_idx)] = op
            else:
                # Shared prefix: the edge operator should be identical, not accumulated.
                if not np.allclose(old, op, atol=tol, rtol=0.0):
                    raise RuntimeError("Internal inconsistency in prefix-tree construction.")

            prefix = next_prefix

        # Last site goes to a single sink state of dimension 1
        cur_idx = prefix_layers[K - 1][prefix]
        last_op = coeff * _key_to_mat(path[K - 1])

        if (cur_idx, 0) in transitions[K - 1]:
            transitions[K - 1][(cur_idx, 0)] += last_op
        else:
            transitions[K - 1][(cur_idx, 0)] = last_op

    # Build the actual MPO tensors
    dims_left = [len(prefix_layers[i]) for i in range(K)]
    dims_right = [len(prefix_layers[i + 1]) for i in range(K - 1)] + [1]

    Ws = []
    for i in range(K):
        W = np.zeros((dims_left[i], dims_right[i], 2, 2), dtype=dtype)
        for (a, b), op in transitions[i].items():
            W[a, b] += op
        W[np.abs(W) < tol] = 0.0
        Ws.append(W)

    return Ws



# ----------- comperssed MPO constructor  ---------------------

# Chan/Keller normal/complementary-operator construction (or we can
# compress the generic MPO afterward


## # =========================
## # antisymmetrized two-body tensor
## # =========================
##
## def antisym_w(I2: np.ndarray) -> np.ndarray:
##     """
##     w[p,q,r,s] = I[p,q,r,s] - I[q,p,r,s]
##                = I[p,q,r,s] - I[p,q,s,r]
##     Works for unrestricted general tensors too.
##     """
##     return I2 - np.swapaxes(I2, 0, 1)
##
##
## # =========================
## # bond-channel bookkeeping
## # =========================
##
## @dataclass(frozen=True)
## class Channel:
##     kind: str
##     inds: Tuple[int, ...] = ()
##
## def right_channel_basis(K: int, k: int) -> List[Channel]:
##     """
##     Channel basis on bond between sites [0..k] and [k+1..K-1].
##
##     Right-complementary layout:
##       H
##       a(q)          q>k
##       adag(q)       q>k
##       P(p,q)        all p,q
##       Q(p,q)        all p,q
##       S(p)          all p
##       I
##
##     This is the Chan right-block vector O^R_k in explicit indexed form.
##     """
##     basis = [Channel("H")]
##     for q in range(k + 1, K):
##         basis.append(Channel("a", (q,)))
##     for q in range(k + 1, K):
##         basis.append(Channel("adag", (q,)))
##     for p in range(K):
##         for q in range(K):
##             basis.append(Channel("P", (p, q)))
##     for p in range(K):
##         for q in range(K):
##             basis.append(Channel("Q", (p, q)))
##     for p in range(K):
##         basis.append(Channel("S", (p,)))
##     basis.append(Channel("I"))
##     return basis
##
##
## def left_channel_basis(K: int, k: int) -> List[Channel]:
##     """
##     Channel basis on bond between sites [0..k-1] and [k..K-1].
##
##     We use the basis on the *incoming* side of W[k], i.e. bond k-1.
##     """
##     return right_channel_basis(K, k - 1) if k > 0 else [Channel("I")]
##
##
## def channel_index(basis: List[Channel]) -> Dict[Channel, int]:
##     return {ch: i for i, ch in enumerate(basis)}
##
## # =========================
## # local one-site contributions
## # =========================
##
## def onsite_hamiltonian(k: int, h1: np.ndarray, I2: np.ndarray, ops: Dict[str, np.ndarray]) -> np.ndarray:
##     """
##     One-site operator contributions acting only on site k.
##
##     For one spin-orbital/site:
##       a_k^\dagger a_k = n_k
##       a_k^\dagger a_k^\dagger a_k a_k = 0
##     so only h[k,k] n_k survives locally.
##     """
##     return h1[k, k] * ops["n"]
##
##
## # =========================
## # Chan/Keller right-block recursions in JW local form
## # =========================
##
## def make_site_W(
##     k: int,
##     h1: np.ndarray,
##     I2: np.ndarray,
##     tol: float = 1e-14,
##     dtype=np.complex128,
## ) -> Tuple[np.ndarray, List[Channel], List[Channel]]:
##     """
##     Build the explicit operator-valued matrix W[k] that maps O^R_k -> O^R_{k-1}.
##
##     Returns
##     -------
##     W : ndarray
##         shape (Dl, Dr, 2, 2)
##     left_basis : list[Channel]
##     right_basis : list[Channel]
##
##     Notes
##     -----
##     This is the right-complementary version based on the channel families
##     H / a / adag / P / Q / S / I.
##     """
##     K = h1.shape[0]
##     assert h1.shape == (K, K)
##     assert I2.shape == (K, K, K, K)
##
##     ops = local_fermion_ops(dtype)
##     I = ops["I"]
##     F = ops["F"]
##     c = ops["c"]
##     cd = ops["cd"]
##     n = ops["n"]
##     z = ops["0"]
##
##     w = antisym_w(I2).astype(dtype, copy=False)
##
##     left_basis = left_channel_basis(K, k)
##     right_basis = right_channel_basis(K, k)
##
##     il = channel_index(left_basis)
##     ir = channel_index(right_basis)
##
##     Dl = len(left_basis)
##     Dr = len(right_basis)
##     W = np.zeros((Dl, Dr, 2, 2), dtype=dtype)
##
##     def add(lch: Channel, rch: Channel, op: np.ndarray):
##         if np.max(np.abs(op)) > tol:
##             W[il[lch], ir[rch]] += op
##
##     # -----------------------------------------
##     # boundary k = 0 : incoming basis is just [I]
##     # We directly create the whole outgoing right-channel vector at cut 0.
##     # -----------------------------------------
##     if k == 0:
##         lI = Channel("I")
##
##         # H_0^R
##         add(lI, Channel("H"), I)
##
##         # a(q), adag(q) for q > 0 pick up parity F on site 0 in JW form
##         for q in range(1, K):
##             add(lI, Channel("a", (q,)), F)
##             add(lI, Channel("adag", (q,)), F)
##
##         # P, Q, S, I propagate trivially through site 0
##         for p in range(K):
##             for q in range(K):
##                 add(lI, Channel("P", (p, q)), I)
##                 add(lI, Channel("Q", (p, q)), I)
##         for p in range(K):
##             add(lI, Channel("S", (p,)), I)
##
##         add(lI, Channel("I"), I)
##         # print(f"DEBUG: W at site {k} is", W.shape)
##         return W, left_basis, right_basis
##
##     # -----------------------------------------
##     # generic recursion from bond k-1 <- k
##     # -----------------------------------------
##     # 1) Propagation of H, P, Q, S, I channels
##     # Chan's generic blocking rule is of the form
##     #   O^R_{k-1} = W[k] O^R_k
##     # with Eq. (25), and P recursion Eq. (36). :contentReference[oaicite:2]{index=2}
##
##     # Identity channel
##     add(Channel("I"), Channel("I"), I)
##
##     # a(q), adag(q) channels:
##     # for q > k, moving one site left prepends parity F on site k.
##     for q in range(k + 1, K):
##         add(Channel("a", (q,)), Channel("a", (q,)), F)
##         add(Channel("adag", (q,)), Channel("adag", (q,)), F)
##
##     # New local a(k), adag(k) do not exist on the right side of cut k,
##     # because right basis starts at q>k only.
##
##     # P(p,q) recursion:
##     #   P^{R_{k-1}}_{pq} = 1_k ⊗ P^{R_k}_{pq} + sum_{s>k} w[p,q,k,s] a_k ⊗ a_s
##     # For one mode/site, the purely local a_k a_k term vanishes.
##     for p in range(K):
##         for q in range(K):
##             chP = Channel("P", (p, q))
##             add(chP, chP, I)
##             for s in range(k + 1, K):
##                 coeff = w[p, q, k, s]
##                 if abs(coeff) > tol:
##                     add(chP, Channel("a", (s,)), coeff * c)
##
##     # Q(p,q) recursion:
##     #   Q^{R_{k-1}}_{pq}
##     # = 1_k ⊗ Q^{R_k}_{pq}
##     # + sum_{s>k} w[p,k,q,s] a_k^\dagger ⊗ a_s
##     # + sum_{r>k} w[p,r,q,k] F_k ⊗ a_r^\dagger * a_k(local closure -> c)
##     # + w[p,k,q,k] n_k
##     #
##     # In the strict Chan notation Q_pq = sum_rs w_prqs a_r^\dagger a_s. :contentReference[oaicite:3]{index=3}
##     for p in range(K):
##         for q in range(K):
##             chQ = Channel("Q", (p, q))
##             add(chQ, chQ, I)
##
##             # r = k, s > k   -> a_k^\dagger a_s
##             for s in range(k + 1, K):
##                 coeff = w[p, k, q, s]
##                 if abs(coeff) > tol:
##                     add(chQ, Channel("a", (s,)), coeff * cd)
##
##             # r > k, s = k   -> a_r^\dagger a_k
##             # moving one site left gives local c with right adag(r)
##             for r in range(k + 1, K):
##                 coeff = w[p, r, q, k]
##                 if abs(coeff) > tol:
##                     add(chQ, Channel("adag", (r,)), coeff * c)
##
##             # local r=s=k
##             coeff = w[p, k, q, k]
##             if abs(coeff) > tol:
##                 add(chQ, Channel("I"), coeff * n)
##
##     # S(p) recursion:
##     #   S_p^{R_{k-1}}
##     # = 1_k ⊗ S_p^{R_k}
##     # + h[p,k] a_k
##     # + sum_{r,s>k} w[p,k,r,s] a_k^\dagger a_r a_s
##     # + sum_{q>k,s>k} w[p,q,k,s] a_q^\dagger a_k a_s
##     # + sum_{q,r>k} w[p,q,r,k] a_q^\dagger a_r a_k
##     #
##     # We route these through existing right channels:
##     #   a(s), P(q,?), Q(?,?), etc.
##     #
##     # This is the key place where the S/A/B/P/Q structure pays off:
##     # S closes one-body pieces directly and uses P/Q-like channels for quartics.
##     for p in range(K):
##         chS = Channel("S", (p,))
##         add(chS, chS, I)
## 
##         # one-body local term h[p,k] a_k
##         coeff = h1[p, k]
##         if abs(coeff) > tol:
##             add(chS, Channel("I"), coeff * c)
## 
##         # term with q = k: sum_{r,s>k} w[p,k,r,s] a_k^\dagger a_r a_s
##         # route through P(r,s)-like open pair-annihilation channel
##         for r in range(K):
##             for s in range(K):
##                 # only useful when right recursion can close it later
##                 coeff = w[p, k, r, s]
##                 if abs(coeff) > tol:
##                     add(chS, Channel("P", (r, s)), coeff * cd)
## 
##         # term with r = k or s = k route through Q channel
##         # indices follow Q_{q,r} = sum_{u,v} w[q,u,r,v] a_u^\dagger a_v
##         for q in range(K):
##             for s in range(K):
##                 coeff = w[p, q, k, s]
##                 if abs(coeff) > tol:
##                     add(chS, Channel("Q", (q, s)), coeff * c)
##                 coeff = w[p, q, s, k]
##                 if abs(coeff) > tol:
##                     add(chS, Channel("Q", (q, s)), coeff * c)
## 
##     # H recursion:
##     #   H^{R_{k-1}}
##     # = 1_k ⊗ H^{R_k}
##     # + h[k,k] n_k
##     # + 1/2 sum_{p<k? handled from left in decomposition}
##     # + closures from S,Q,P channels on the current site
##     #
##     # In the right-complementary construction, H collects exactly the local
##     # closures of the open right channels.
##     add(Channel("H"), Channel("H"), I)
##     add(Channel("H"), Channel("I"), onsite_hamiltonian(k, h1, I2, ops))
## 
##     # close one-body terms h[k,q] a_k^\dag a_q and h[q,k] a_q^\dag a_k through S
##     for p in range(K):
##         # 1/2 * a_k^\dag S_k  + h.c.
##         if p == k:
##             add(Channel("H"), Channel("S", (p,)), 0.5 * cd)
##             # hermitian conjugate contribution
##             add(Channel("H"), Channel("S", (p,)), 0.5 * c)
## 
##     # close two-index channels:
##     # +1/2 A_{kk?} P  vanishes on one spin-orbital/site,
##     # -1/2 B_{kk}=n_k couples to Q_{kk}
##     add(Channel("H"), Channel("Q", (k, k)), -0.5 * n)
## 
##     return W, left_basis, right_basis
## 
## 
## def build_chan_keller_mpo(
##     h1: np.ndarray,
##     I2: np.ndarray,
##     tol: float = 1e-14,
##     dtype=np.complex128,
## ) -> Tuple[List[np.ndarray], List[List[Channel]]]:
##     """
##     Build a Chan/Keller-style chemistry MPO with explicit S/A/B/P/Q-family channels.
## 
##     Returns
##     -------
##     Ws : list of ndarray
##         Ws[k] has shape (D_left_k, D_right_k, 2, 2)
##     bases : list of right-bond bases
##         bases[k] is the right-bond basis after site k
##     """
##     h1 = np.asarray(h1, dtype=dtype)
##     I2 = np.asarray(I2, dtype=dtype)
##     K = h1.shape[0]
##     if h1.shape != (K, K):
##         raise ValueError("h1 must be shape (K,K)")
##     if I2.shape != (K, K, K, K):
##         raise ValueError("I2 must be shape (K,K,K,K)")
## 
##     Ws = []
##     right_bases = []
##     for k in range(K):
##         Wk, _, rb = make_site_W(k, h1, I2, tol=tol, dtype=dtype)
##         Ws.append(Wk)
##         right_bases.append(rb)
##     return Ws, right_bases
## 
## def right_boundary_vector(right_basis, dtype=np.complex128):
##     idx = {ch: i for i, ch in enumerate(right_basis)}
##     v = np.zeros(len(right_basis), dtype=dtype)
##     v[idx[Channel("I")]] = 1.0
##     return v
## 
## def close_right_boundary(Ws, right_bases):
##     vR = right_boundary_vector(right_bases[-1], dtype=Ws[-1].dtype)
##     Wlast = np.tensordot(Ws[-1], vR, axes=(1, 0))   # (Dl, 2, 2)
##     Wlast = Wlast[:, None, :, :]                    # (Dl, 1, 2, 2)
##     return Ws[:-1] + [Wlast]


# ------------------------------- new comperssed -------------------------

@dataclass(frozen=True)
class BondLabel:
    """
    Meaning of one MPO bond state.

    kind:
      START : left boundary
      STOP  : right boundary
      CONST : constant-operator propagation channel
      L     : fork label = operators already applied on the left
      R     : merge label = operators still to be applied on the right

    payload:
      tuple of (site_index, mat_key) pairs
    """
    kind: str
    payload: Tuple[Tuple[int, Tuple[complex, ...]], ...] = ()


def _collect_local_term_strings(h1, h2, tol=1e-14, dtype=np.complex128):
    r"""
    Collect unique local JW operator strings for

    .. math::

        H =
        \sum_{pq} h_{pq} a_p^\dagger a_q
        + {1 \over 2}\sum_{pqrs} h_{pqrs}
          a_p^\dagger a_q^\dagger a_r a_s.

    This is the common front-end used by the generic and compact chemistry MPO
    builders.  It performs the Jordan-Wigner transformation, drops zero
    nilpotent strings, and combines duplicate product operators.

    Returns
    -------
    term_strings : list[tuple[complex, list[np.ndarray]]]
        Each item is (coeff, local_ops), where local_ops[i] is the 2x2
        operator on site i for one full term string.
    """
    h1 = np.asarray(h1, dtype=dtype)
    h2 = np.asarray(h2, dtype=dtype)

    if h1.ndim != 2 or h1.shape[0] != h1.shape[1]:
        raise ValueError("h1 must have shape (K, K)")
    K = h1.shape[0]

    if h2.shape != (K, K, K, K):
        raise ValueError("h2 must have shape (K, K, K, K)")

    path_coeff = defaultdict(complex)

    def add_term(coeff, fermion_ops):
        coeff = complex(coeff)
        if abs(coeff) < tol:
            return

        local = jw_local_string(K, fermion_ops, dtype=dtype)

        # Drop nilpotent terms, e.g. c^2 = 0
        if any(np.all(np.abs(op) < tol) for op in local):
            return

        path = tuple(_mat_key(op, tol=tol) for op in local)
        # print("debug: path = ", path)
        path_coeff[path] += coeff

    # one-body terms
    for p, q in np.argwhere(np.abs(h1) > tol):
        add_term(h1[p, q], [(p, True), (q, False)])

    # two-body terms
    for p, q, r, s in np.argwhere(np.abs(h2) > tol):
        add_term(0.5 * h2[p, q, r, s],
                 [(p, True), (q, True), (r, False), (s, False)])

    term_strings = []
    for path, coeff in path_coeff.items():
        if abs(coeff) <= tol:
            continue
        local_ops = [_key_to_mat(key) for key in path]
        term_strings.append((coeff, local_ops))

    return term_strings


def _nonidentity_pairs(local_ops, tol=1e-14):
    """
    Return the non-identity local operators of a term as
    ((site, mat_key), ...).
    """
    d = local_ops[0].shape[0]
    Ikey = _mat_key(np.eye(d, dtype=np.complex128), tol=tol)

    pairs = []
    for i, op in enumerate(local_ops):
        key = _mat_key(op, tol=tol)
        if key != Ikey:
            pairs.append((i, key))
    return tuple(pairs)


def _bond_label_for_term(pairs, bond, switch_site, n_sites):
    """
    Label on a given bond for one term.

    bond = 0..n_sites
    """
    if bond == 0:
        return BondLabel("START")
    if bond == n_sites:
        return BondLabel("STOP")

    if bond <= switch_site:
        # fork label: identify what has already been applied on the left
        left_payload = tuple((pos, key) for pos, key in pairs if pos < bond)
        return BondLabel("L", left_payload)

    # merge label: identify what remains to be applied on the right
    right_payload = tuple((pos, key) for pos, key in pairs if pos >= bond)
    return BondLabel("R", right_payload)


def _label_sort_key(label: BondLabel):
    kind_order = {
        "START": 0,
        "CONST": 1,
        "L": 2,
        "R": 3,
        "STOP": 4,
    }
    return (kind_order.get(label.kind, 99), repr(label.payload))


def build_compact_second_quantized_mpo(
    h1,
    h2,
    constant=0.0,
    tol=1e-14,
    dtype=np.complex128,
):
    r"""
    Build a compact, exact, open-boundary MPO for

    .. math::

        H = C_0 I
        + \sum_{pq} h_{pq} a_p^\dagger a_q
        + {1 \over 2}\sum_{pqrs} h_{pqrs}
          a_p^\dagger a_q^\dagger a_r a_s,

    where :math:`C_0` is a constant shift.

    It starts from the same local-string expansion as
    :func:`second_quantized_to_mpo`,

    .. math::

        H-C_0I =
        \sum_\ell \alpha_\ell
        O^{(\ell)}_0 \otimes O^{(\ell)}_1 \otimes \cdots
        \otimes O^{(\ell)}_{K-1},

    but stores a term on bond :math:`b` by either its already-applied left
    substring or its still-needed right substring.  For each term, a
    ``switch_site`` near the middle of the non-identity support is chosen; the
    scalar coefficient :math:`\alpha_\ell` is placed only on that site.  Shared
    left and right substrings are then reused across many terms, giving a
    smaller exact MPO than the pure prefix tree in many dense ab initio cases.

    Returns
    -------
    Ws : list[np.ndarray]
        Ws[i] has shape (D_i, D_{i+1}, 2, 2), with true OBC:
        Ws[0].shape[0]  == 1
        Ws[-1].shape[1] == 1

    bond_labels : list[list[BondLabel]]
        bond_labels[b] is the list of bond states on bond b, b = 0..K.
        The tensor Ws[i][a, b] maps
        bond_labels[i][a] -> bond_labels[i+1][b].
    """
    h1 = np.asarray(h1, dtype=dtype)
    h2 = np.asarray(h2, dtype=dtype)

    if h1.ndim != 2 or h1.shape[0] != h1.shape[1]:
        raise ValueError("h1 must have shape (K, K)")
    K = h1.shape[0]

    # TODO: use chols to reduce memeory
    if h2.shape != (K, K, K, K):
        raise ValueError("h2 must have shape (K, K, K, K)")

    I2 = np.eye(2, dtype=dtype)

    # States living on each bond 0..K
    bond_state_sets = [set() for _ in range(K + 1)]
    bond_state_sets[0].add(BondLabel("START"))
    bond_state_sets[K].add(BondLabel("STOP"))

    # edge_ops[i][(left_label, right_label)] = 2x2 local operator block
    edge_ops = [dict() for _ in range(K)]

    def add_edge(site, left_label, right_label, op, *, accumulate):
        key = (left_label, right_label)

        if key not in edge_ops[site]:
            edge_ops[site][key] = np.array(op, copy=True)
            return

        if accumulate:
            edge_ops[site][key] += op
            return

        old = edge_ops[site][key]
        if not np.allclose(old, op, atol=tol, rtol=0.0):
            raise RuntimeError(
                f"Bond-label collision on non-switch edge at site {site}: "
                f"{left_label} -> {right_label}. "
                "This means the label set is too coarse for this edge."
            )
        # Shared substring: keep only one copy, do not sum.

    # Build all non-constant term strings
    term_strings = _collect_local_term_strings(h1, h2, tol=tol, dtype=dtype)
    print("\nDebug: number of local term string: ", len(term_strings))

    # Accumulate exact compact transitions
    for coeff, local_ops in term_strings:
        pairs = _nonidentity_pairs(local_ops, tol=tol)

        # If a term collapses to pure identity, absorb it into the constant
        if len(pairs) == 0:
            constant += coeff
            continue

        # Switch after the "middle" non-identity operator.
        # For 1,2,3,4 non-identity sites this gives ranks 0,0,1,1 respectively,
        # so each label stores at most two non-identity operators on one side.
        switch_rank = (len(pairs) - 1) // 2
        switch_site = pairs[switch_rank][0]

        for bond in range(K + 1):
            bond_state_sets[bond].add(
                _bond_label_for_term(pairs, bond, switch_site, K)
            )

        for site in range(K):
            left_label = _bond_label_for_term(pairs, site, switch_site, K)
            right_label = _bond_label_for_term(pairs, site + 1, switch_site, K)
            print(f"\nleft_label  [{site}] ", left_label)
            print(f"right_label [{site}] ", right_label)
            print(f"local_ops   [{site}] ", local_ops[site])

            if site == switch_site:
                # Put the scalar coefficient on exactly one site.
                add_edge(
                    site,
                    left_label,
                    right_label,
                    coeff * local_ops[site],
                    accumulate=True,
                )
            else:
                # Shared prefix/suffix edge: keep once, do not sum.
                add_edge(
                    site,
                    left_label,
                    right_label,
                    local_ops[site],
                    accumulate=False,
                )

    # Optional constant term
    if abs(constant) > tol:
        if K == 1:
            add_edge(
                0,
                BondLabel("START"),
                BondLabel("STOP"),
                constant * I2,
                accumulate=True,
            )
        else:
            const_label = BondLabel("CONST")
            for bond in range(1, K):
                bond_state_sets[bond].add(const_label)

            add_edge(
                0,
                BondLabel("START"),
                const_label,
                constant * I2,
                accumulate=True,
            )
            for site in range(1, K - 1):
                add_edge(
                    site,
                    const_label,
                    const_label,
                    I2,
                    accumulate=False,
                )
            add_edge(
                K - 1,
                const_label,
                BondLabel("STOP"),
                I2,
                accumulate=False,
            )

    # Enumerate states on each bond
    bond_labels = []
    bond_index = []
    for bond in range(K + 1):
        labels = sorted(bond_state_sets[bond], key=_label_sort_key)
        bond_labels.append(labels)
        bond_index.append({lab: i for i, lab in enumerate(labels)})

    # True OBC sanity checks
    if bond_labels[0] != [BondLabel("START")]:
        raise RuntimeError("Left boundary is not one-dimensional.")
    if bond_labels[-1] != [BondLabel("STOP")]:
        raise RuntimeError("Right boundary is not one-dimensional.")

    # Build dense local MPO tensors
    Ws = []
    for site in range(K):
        Dl = len(bond_labels[site])
        Dr = len(bond_labels[site + 1])
        W = np.zeros((Dl, Dr, 2, 2), dtype=dtype)

        for (left_label, right_label), op in edge_ops[site].items():
            a = bond_index[site][left_label]
            b = bond_index[site + 1][right_label]
            W[a, b] += op

        W[np.abs(W) < tol] = 0.0
        Ws.append(W)

    return Ws, bond_labels

# ------------------------------------------------------------------------


# ---------- other functions --------------------

def _kron_all(local_ops):
    out = np.array([[1.0]], dtype=np.complex128)
    for op in local_ops:
        out = np.kron(out, op)
    return out


def _dense_ladder_operators(n_sites, dtype=np.complex128):
    # I, F, c, _ = _site_ops(dtype=dtype)

    ops = local_fermion_ops(dtype)
    I = ops["I"]
    F = ops["F"]
    c = ops["c"]

    a_ops = []
    for p in range(n_sites):
        local = []
        for i in range(n_sites):
            if i < p:
                local.append(F)
            elif i == p:
                local.append(c)
            else:
                local.append(I)
        a_p = _kron_all(local)
        a_ops.append(a_p)
    adag_ops = [a.conj().T for a in a_ops]
    return a_ops, adag_ops


def _dense_hamiltonian_from_integrals(h1, h2, tol=1e-14, dtype=np.complex128):
    h1 = np.asarray(h1, dtype=dtype)
    h2 = np.asarray(h2, dtype=dtype)
    n_sites = h1.shape[0]
    dim = 2 ** n_sites
    H = np.zeros((dim, dim), dtype=dtype)
    a_ops, adag_ops = _dense_ladder_operators(n_sites, dtype=dtype)

    for p, q in np.argwhere(np.abs(h1) > tol):
        H += h1[p, q] * (adag_ops[p] @ a_ops[q])

    for p, q, r, s in np.argwhere(np.abs(h2) > tol):
        H += 0.5 * h2[p, q, r, s] * (adag_ops[p] @ adag_ops[q] @ a_ops[r] @ a_ops[s])

    return H


def _dense_from_mpo(Ws, tol=1e-14, dtype=np.complex128):
    partial = {0: np.array([[1.0]], dtype=dtype)}
    for i, W in enumerate(Ws):
        _, Dr, _, _ = W.shape
        nxt = {}
        for a, left in partial.items():
            for b in range(Dr):
                block = W[a, b]
                if np.max(np.abs(block)) <= tol:
                    continue
                term = np.kron(left, block)
                if b in nxt:
                    nxt[b] += term
                else:
                    nxt[b] = term
        if not nxt:
            raise RuntimeError(f"MPO has no active transitions at site {i}")
        partial = nxt

    if 0 not in partial:
        raise RuntimeError("Final MPO bond does not contain sink index 0")

    return partial[0]


def _n2_pyscf_spin_orbital_integrals(active_spatial_orbitals=2, bond_length_angstrom=1.1):
    try:
        from pyscf import gto, scf, ao2mo
    except ImportError as exc:
        raise ImportError("PySCF is required for the N2 test. Install with: pip install pyscf") from exc

    mol = gto.Mole()
    mol.atom = f"N 0.0 0.0 0.0; N 0.0 0.0 {bond_length_angstrom}"
    mol.unit = "Angstrom"
    mol.basis = "sto-3g"
    mol.spin = 0
    mol.charge = 0
    mol.verbose = 0
    mol.build()

    mf = scf.RHF(mol)
    mf.conv_tol = 1e-12
    mf.kernel()
    if not mf.converged:
        raise RuntimeError("PySCF RHF did not converge for N2 test.")

    C = mf.mo_coeff
    n_mo = C.shape[1]
    if active_spatial_orbitals > n_mo:
        raise ValueError(
            f"Requested {active_spatial_orbitals} active orbitals but only {n_mo} MOs available."
        )

    hcore_ao = mf.get_hcore()
    h1_mo = C.T @ hcore_ao @ C

    eri_mo = ao2mo.restore(1, ao2mo.kernel(mol, C), n_mo)

    idx = np.arange(active_spatial_orbitals)
    h1_spatial = h1_mo[np.ix_(idx, idx)]
    eri_spatial = eri_mo[np.ix_(idx, idx, idx, idx)]

    n_spin = 2 * active_spatial_orbitals
    h1 = np.zeros((n_spin, n_spin), dtype=np.complex128)
    h2 = np.zeros((n_spin, n_spin, n_spin, n_spin), dtype=np.complex128)

    for p in range(active_spatial_orbitals):
        for q in range(active_spatial_orbitals):
            h1[2 * p, 2 * q] = h1_spatial[p, q]
            h1[2 * p + 1, 2 * q + 1] = h1_spatial[p, q]

    # Spin-orbital two-electron tensor for operator order a_p^† a_q^† a_r a_s
    # using spin-conserving Coulomb integrals from the RHF spatial MO basis.
    h2[0::2, 0::2, 0::2, 0::2] = eri_spatial  # sigma=0, tau=0
    h2[0::2, 1::2, 1::2, 0::2] = eri_spatial  # sigma=0, tau=1
    h2[1::2, 0::2, 0::2, 1::2] = eri_spatial  # sigma=1, tau=0
    h2[1::2, 1::2, 1::2, 1::2] = eri_spatial  # sigma=1, tau=1

    return h1, h2

def _test_second_quantized_to_mpo_with_n2():
    tol = 1e-12
    h1, h2 = _n2_pyscf_spin_orbital_integrals(active_spatial_orbitals=2, bond_length_angstrom=1.1)
    Ws = second_quantized_to_mpo(h1, h2, tol=tol, dtype=np.complex128)

    H_from_mpo = _dense_from_mpo(Ws, tol=tol, dtype=np.complex128)
    H_ref = _dense_hamiltonian_from_integrals(h1, h2, tol=tol, dtype=np.complex128)

    err = np.linalg.norm(H_from_mpo - H_ref)
    max_abs = np.max(np.abs(H_from_mpo - H_ref))
    if not np.allclose(H_from_mpo, H_ref, atol=1e-9, rtol=1e-9):
        raise AssertionError(
            "N2/PySCF second_quantized_to_mpo test failed: "
            f"frobenius_err={err:.3e}, max_abs_err={max_abs:.3e}"
        )

    print(
        "N2/PySCF second_quantized_to_mpo test passed: "
        f"K={h1.shape[0]}, Frobenius error={err:.3e}, max abs error={max_abs:.3e}"
    )



if __name__ == "__main__":
    try:
        _test_second_quantized_to_mpo_with_n2()
    except ImportError as exc:
        raise SystemExit(str(exc)) from exc
